[project]
name = "quickfitter"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "lmfit>=1.3.4",
    "numpy>=2.3.2",
    "pandas>=2.3.1",
    "scipy>=1.16.1",
]
